### ISSUE TITLE
[Bug] – v1.0.1 is broken for Firefox

### ISSUE THREAD

**Issue by gmargaritis** [dephraiim/minimal-youtube#13]
`Firefox: v106.0.1 (64-bit)`

Trying to load the extension with `v1.0.1`, as described in the instructions, leads to the following error:

```console
File /path/minimal-youtube-1.0.1.zip does not contain a valid manifest
```

`v1.0.0` works great

**Comment by dephraiim** [comment]
I have uploaded the correct asset file. Everything should work now
